### ISSUE TITLE
Pasirašytų failų atsisiuntimas

### ISSUE THREAD

**Issue by edgaras1337** [registrucentras/gosign-api-integration#10]
Sveiki, testuojant multisign servisą, failai pasirašo, tačiau po pasirašymo, kreipiantis į jūsų pateiktą nuorodą jiems atsisiųsti, gaunu klaidą "Response status code does not indicate success: 500 (Internal Server Error)". Kaip suprantu, čia klaida jūsų serveryje.

**Comment by registrucentras** [comment]
Sveiki, kreipkitės bendru pagalbos paštu su problemos aprašymų [info@registrucentras.lt](mailto:info@registrucentras.lt).
