### ISSUE TITLE
Peradresavimas po pasirašymo

### ISSUE THREAD

**Issue by edgaras1337** [registrucentras/gosign-api-integration#11]
Sveiki, noriu paklausti, ar neįmanoma padaryti taip, kad po pasirašymo, GoSign automatiškai peradresuotų į responseUrl, ir nereikėtų spausti mygtuko "Grįžti į dokumentų sąrašą"?

**Comment by registrucentras** [comment]
Sveiki,

esame numatę tokį šabloną ir greitu metu paleisime.
