### ISSUE TITLE
Failed to validate request: 'document' value is not a valid PDF

### ISSUE THREAD

**Issue by e-stankevicius** [registrucentras/gosign-api-integration#2]
Isbandem kelis PDF. 

![image](https://user-images.githubusercontent.com/766148/134127365-25e90fee-7291-4465-b500-06ed20138d18.png)

**Comment by registrucentras** [comment]
@OO00O0O dauguma klientų naudoja [SoapClient](https://www.php.net/manual/en/class.soapclient.php), ši biblioteka parsina wsdl, kuriame documentDigest, file content ir panašūs elementai yra [base64Binary](https://www.w3.org/TR/xmlschema-2/#base64Binary) tipo. Tokiu atveju jums nebereikia dar kartą base64encodinti šių parametrų, nes tai padaro pati biblioteka. gaunasi 2x base64encode.
