### ISSUE TITLE
Pasirašymo žymos šrifto dydis

### ISSUE THREAD

**Issue by ausraurb** [registrucentras/gosign-api-integration#3]
Ar galima dokumente valdyti pasirašymo žymos dydį? Kokie parametrai tai aprašo
Pvz.
_Dokumentą elektroniniu parašu pasirašė AUŠRA URBAITYTĖ
Data: 2021-08-25 14:29:23
Paskirtis: Įgaliotas pasirašyti LSMU Rektoriaus 2020..._

(naudojama multisign)

**Comment by registrucentras** [comment]
Sveiki,
jei kalbate apie parašo atvaizdavimo konteinerio dydį, tai galite, kaip ir poziciją, nurodyti position elemente, width ir height elementai:
https://registrucentras.github.io/gosign-api-integration/position.html#position-elementas

tokiu būdu proporcingai sumažinsite ir šriftą

**Comment by ausraurb** [comment]
Sveiki, 
Ačiū, pavyko.
