### ISSUE TITLE
Raktas

### ISSUE THREAD

**Issue by edgaras1337** [registrucentras/gosign-api-integration#6]
Norėjome patestuoti pasirašymo servisą, panaudojome Jūsų dokumentacijoje pateiktą kliento ID: "StandardTestClientID", bei duotą privatų raktą, kad sugeneruoti signature elementą, tačiau gaunama klaida, kad parašas, yra per trumpas, turėtų būti 256-bit, o yra 128-bit. Naudojant savo RSA sugeneruotą 256-bit ilgio raktą, gaunu klaidą, kad netinkamas signature elementas, bet ilgis tinka.

![image](https://user-images.githubusercontent.com/84501914/170227911-e77a79fd-99ba-4011-b5b8-b7ceb41a9158.png)
![image](https://user-images.githubusercontent.com/84501914/170223626-4a2d4c52-0ab6-4b76-898f-456c5ad669f9.png)

**Comment by registrucentras** [comment]
@edgaras1337 sveiki, jei dar gausite klaidą, dėl rakto ilgio, pabandykite sugeneruoti raktus pagal instrukciją
https://registrucentras.github.io/gosign-api-integration/key-generation.html
ir public raktą perduokite mūsų administratoriui. Jei gaunate "invalid signature" klaidą - formuojate blogai pasirašymo "string'ą":
https://registrucentras.github.io/gosign-api-integration/signature.html, jei pasidalintumėte kokį "string'ą" pasirašinėjate, galėtume padėti nustatyti problemą.

**Comment by edgaras1337** [comment]
O norint patestuoti, reikia pirkti paslaugą, ar galima tiesiog nusiųsti raktą administratoriui, ir testavimui skirta paslauga, veiks su testiniu kliento ID: "StandardTestClientID"?

**Comment by registrucentras** [comment]
Sveiki, @edgaras1337 
prašome užpildyti formą https://www.elektroninis.lt/lt/verslui/nid-580, kad norite atlikti testavimą.

Pardavimų vadybininkas susisieks ir sukurs Jums klientą testavimui. Kol atliksite testus, paslauga bus nemokama. Jei po testavimo paslauga tiks, pasirašysime sutartį ir suteiksime prieigą PROD aplinkoje.
