### ISSUE TITLE
Multisign dokumentų siuntimas

### ISSUE THREAD

**Issue by edgaras1337** [registrucentras/gosign-api-integration#8]
Sveiki, pagal dokumentaciją, inicijuojant kelių dokumentų pasirašymą reikia sugeneruoti nuorodą, pagal kurią servisas galės pasiekti dokumentus. 

A toks būdas yra saugus? Dokumentai yra konfidencialūs ir nenorėtume, kad juos galėtų bet kas pasiekti, pagal nuorodą.  Gal įmanoma kaip nors nustatyti, kad būtent GoSign kreipsis į tą nuorodą?

**Comment by registrucentras** [comment]
Sveiki,
taip, `multisign` servisui reikia pateikti nuorodą į dokumentą. Patį dokumentą galite apsaugoti įvairiai, pvz:
kad prieitų prie dokumento, papildomai prie url turėtų pridėti `auth` `hash` parametrą (apsunkinti dokumento radimą arba prieigą):
`https://example.com/dokumentai/documentas-1.pdf?auth=3127143b914e9d595b9a03dd816cea1f`
tokią nuorodą perduoti `multisign` servisui.
Kitas patarimas būtų toks, kad dokumentą prieinamą laikyti tik tiek, kol jį pasiima `unisign` servisas: t.y., gaunate `success` žinutę iš `init` metodo ir dokumentą trinate/naikinate prieigą ar pan.
Šiuo metu, kitokių realizuotų, mūsų pusėje, apsaugos mechanizmų neturime.
