### ISSUE TITLE
Hash algoritmas

### ISSUE THREAD

**Issue by edgaras1337** [registrucentras/gosign-api-integration#9]
Sveiki, šiuo metu naudojame Jūsų testinį GoSign servisą. Dokumentacijoje rašo, kad reikia naudoti SHA256 Hash algoritmą, tačiau testinis servisas su juo neveikia, veikia tik su SHA1.

Taip pat noriu paprašyti RSA viešojo rakto, serviso atsakymų patvirtinimui. Ar jo reikia prašyti to žmogaus, kuris davė prieigą prie serviso?

**Comment by registrucentras** [comment]
Sveiki, jei kalbate apie užklausos pasirašymą, tai ten yra naudojama sha1. Pačiame dokumento pasirašyme naudojama sha256, bet šios vietos klientas pats parametrizuoti negali. Public raktą turėtų suteikti mūsų administratorius, kuris ir kontroliuoja prieigą.
